#!/bin/bash
script_dir="$(cd "$(dirname "${BASH_SOURCE:-${(%):-%N}}")"; pwd)"
cd "$script_dir"

# show https://docs.docker.com/engine/install/ubuntu/
if [ ! -x "$(command -v docker)" ]; then
  sudo apt update
  sudo apt install -y ca-certificates curl gnupg lsb-release
fi

if [ ! -e "/usr/share/keyrings/docker-archive-keyring.gpg" ]; then
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
fi

if [ ! -e "/etc/apt/sources.list.d/docker.list" ]; then
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
fi

if [ ! -x "$(command -v docker)" ]; then
  sudo apt update
  sudo apt install -y docker-ce docker-ce-cli containerd.io
fi

# show https://docs.docker.com/compose/install/
if [ ! -x "$(command -v docker-compose)" ]; then
  sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  sudo chmod +x /usr/local/bin/docker-compose
fi
