#!/bin/bash
script_dir="$(cd "$(dirname "${BASH_SOURCE:-${(%):-%N}}")"; pwd)"
cd "$script_dir"

if [ ! -x "$(command -v fish)" ]; then
  sudo apt-add-repository ppa:fish-shell/release-3
  sudo apt update
  sudo apt install fish -y
fi
