#!/bin/bash
script_dir="$(cd "$(dirname "${BASH_SOURCE:-${(%):-%N}}")"; pwd)"
cd "$script_dir/.."

if [ ! -x "$(command -v tmux)" ]; then
  sudo apt install tmux -y
fi

# install tpm plugin manager
if [ ! -e "$HOME/.tmux/plugins/tpm" ]; then
  mkdir -p "$HOME/.tmux/plugins"
  git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
fi
