#!/bin/bash

function brew_install () {
  if [ ! -x "$(command -v brew)" ]; then
    echo "homebrew is not yet installed."
    exit 1
  fi

  c="$1"
  p=${2:-$c}
  if [ ! -x "$(command -v $c)" ]; then
    echo "$p is not yet installed. (install)"
    brew install "$p"
  else
    echo "$p is already installed. (upgrade)"
    brew upgrade "$p"
  fi
}
