#!/bin/bash
script_dir="$(cd "$(dirname "${BASH_SOURCE:-${(%):-%N}}")"; pwd)"

brew install tmux

# install tpm plugin manager
if [ ! -e "$HOME/.tmux/plugins/tpm" ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

f="tmux.osx.conf"
cd "$script_dir/../.config/tmux/"
mkdir -p "$HOME/.config/tmux"
ln -sfv "$(pwd)/$f" "$HOME/.config/tmux/$f"
