#!/bin/bash
script_dir="$(cd "$(dirname "${BASH_SOURCE:-${(%):-%N}}")"; pwd)"
cd "$script_dir"

# install tmux command
. common
brew_install tmux

# install tpm plugin manager
if [ ! -e "$HOME/.tmux/plugins/tpm" ]; then
  mkdir -p "$HOME/.tmux/plugins"
  git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
fi

# set config file
f="tmux.osx.conf"
script_dir="$(cd "$(dirname "${BASH_SOURCE:-${(%):-%N}}")"; pwd)"
cd "$script_dir/../.config/tmux/"
mkdir -p "$HOME/.config/tmux"
ln -sfv "$(pwd)/$f" "$HOME/.config/tmux/$f"
