#!/bin/bash
script_dir="$(cd "$(dirname "${BASH_SOURCE:-${(%):-%N}}")"; pwd)"
cd "$script_dir"

. common
brew_install yabai
brew_install skhd

cd "$script_dir/../.config/home"
for f in ".yabairc" ".skhdrc"
do
  ln -sfv "$(pwd)/$f" "$HOME/$f"
done

if [ -x "$(command -v yabai)" ]; then
  brew services start yabai
fi

if [ -x "$(command -v skhd)" ]; then
  brew services start skhd
fi
